language: python

sudo: false

cache:
  directories:
    - $HOME/.cache/pip

branches:
  except:
    - gh-pages

python:
  - "2.6"
  - "2.7"

# command to install dependencies
install:
    - "pip install matplotlib ipython"
    - "git clone git://github.com/iminuit/iminuit.git; cd iminuit; python setup.py install; cd .."

# command to run tests
script:
    - "python setup.py build_ext -i"
    - "NODISPLAY=1 nosetests"
